version: '3.7'

services:

  webgateway:
    build: ./webgateway
    command: python manage.py runserver 0.0.0.0:8001
    #command: gunicorn proj_webgateway.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./webgateway:/usr/src/app/
    ports:
      - 8001:8001
    env_file:
      - ./config/.env.dev
    depends_on: 
      - webgateway-db
    networks:
      - mediexcel_network


  webgateway-db:
    image: mariadb:10.7.3
    volumes:
      - ./databases/webgateway/backup:/var/lib/mysql
    env_file:
      - ./config/.env.dev
    networks:
      - mediexcel_network

  
networks:
  mediexcel_network:
