# Generated by Django 3.1.2 on 2020-12-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_path', models.CharField(max_length=128, unique=True)),
                ('request_path', models.CharField(max_length=255)),
                ('plugin', models.IntegerField(choices=[(0, 'Remote auth'), (1, 'Token auth')], default=0)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.proyect')),
            ],
        ),
    ]
