# Generated by Django 3.1.2 on 2022-04-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyect',
            new_name='EndPoint',
        ),
    ]
